default:
  tags:
    - node16
  image: maurosoft1973/alpine-lftp
  before_script:
    - /restore_last_git_modified_time.sh
  only:
    - master

stages:
  - deploy-dev
  - deploy-live

variables:
  FTP_REMOTE_FOLDER: 'html/wp-content/plugins/am-hotelfolio-reguest'

.deploy_template: &deploy_script
  script:
    - lftp -e "set ssl:verify-certificate no; set ftp:use-mdtm-overloaded true; open -p 222 $FTP_SERVER; user $FTP_USER '$FTP_PASS'; mirror -X .* -X .*/ --reverse --verbose --delete $PWD $FTP_REMOTE_FOLDER; bye"

deploy-dev-job:
  <<: *deploy_script
  stage: deploy-dev
  environment:
    name: development
    url: https://dev.familyresort.at
  variables:
    FTP_SERVER: 'sftp://dev.familyresort.at'
    FTP_USER: $FAMILYRESORT_DEV_USER
    FTP_PASS: $FAMILYRESORT_DEV_PASS

deploy-live-job:
  <<: *deploy_script
  when: manual
  stage: deploy-live
  environment:
    name: production
    url: https://familyresort.at
  variables:
    FTP_SERVER: 'sftp://familyresort.at'
    FTP_USER: $FAMILYRESORT_LIVE_USER
    FTP_PASS: $FAMILYRESORT_LIVE_PASS